# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-01 22:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_backend', '0002_fileupload_uploaded_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileupload',
            old_name='filename',
            new_name='name',
        ),
    ]
